#!/usr/bin/perl

use v5.36;

my @ranges;
while (<>) {
    chomp;
    last if /\A\z/;
    push @ranges, [ split /-/ ];
}
my $n;
while (my $ingredient = <>) {
    chomp;
    ++$n if grep { $ingredient >= $_->[0] and $ingredient <= $_->[1] } @ranges;
}
say $n;
